[managers.system]
items = [
#
# System
#
  "keyd",
  "neovim",
  "swayfx",
  "luarocks",
  "hererocks",
  "dunst",
  "lua51",

# Nvim
  # Luasnip
  "lua-jsregexp",

#
# Browser
#
  "qutebrowser",
  "python-adblock",

#
# Fuzzy Finder
# 
  "fzf",

#
# Background
#
  "swww",

#
# Font
#
  "ttf-cmu-serif",
  "ttf-intone-nerd",

# 
# Japanese font
#
  "ttf-koruri",
  "fcitx5",
  "fcitx5-configtool",
  "fcitx5-gtk",
  "fcitx5-qt",
  "fcitx5-mozc",

#
# Excel
#
  "pdfjs",
  "libreoffice-fresh",

#
# Screen Capture
#
  "slurp",
  "grim",
  "swayimg",
  "wl-clipboard",
  "wf-recorder",

#
# Wireshark
#
  "wireshark-qt",

#
# Matrix for funsie
#
  "cmatrix",

#
# Music player
#
  "nuclear-player-bin",

#
# YouTube
# 
  "mpv",
  "svp-bin",
  "yt-dlp",
  "zenity",

#
# Image Viewer
#
  "vimiv-qt",

#
# Note taking
#
  "obsidian",
  
  "kitty",
  "imagemagick",

# Steam
  "steam",
  "tree-sitter-markdown",
]
